import logging
import alert_system
import config
import argparse

def main(test_open=None):
    """
    Main entry point for TQQQ Dashboard alerts.
    Fetches data, calculates metrics, generates charts, and sends a dashboard email.
    """
    print("Starting StockAlert App (TQQQ Dashboard)...")
    
    # 0. Check if Market is Open (Today is a trading day)
    if test_open is None and not alert_system.is_market_active():
        logging.info("Exiting because market is closed today.")
        return

    # 1. Fetch Data (2 years for dashboard)
    data = alert_system.fetch_data()
    if data is None or data.empty:
        logging.error("Exiting due to data fetch failure.")
        return

    # 2. Calculate all dashboard metrics
    metrics = alert_system.get_dashboard_metrics(data)
    
    if metrics is None:
        logging.error("Failed to calculate dashboard metrics.")
        return
    
    # Override open price for testing if provided
    if test_open is not None:
        logging.info(f"TEST MODE: Overriding Open {metrics['current_open']} with {test_open}")
        metrics['current_open'] = test_open
        # Re-evaluate SMA status
        if metrics['sma_150']:
            if test_open > metrics['sma_150']:
                metrics['sma_status'] = "ABOVE"
            elif test_open < metrics['sma_150']:
                metrics['sma_status'] = "BELOW"
            else:
                metrics['sma_status'] = "EQUAL"

    # 3. Generate 90-day trend charts
    logging.info("Generating 90-day trend charts...")
    charts = alert_system.generate_trend_charts(data, days=90)
    logging.info(f"Generated {len(charts)} charts")

    # 4. Generate email content
    subject = f"TQQQ Dashboard Alert - {metrics['latest_date']} | {metrics['sma_status']} SMA"
    
    # Plain text fallback
    plain_body = f"""
TQQQ Dashboard - {metrics['latest_date']}
{'='*40}

Current Metrics:
----------------
Latest Date:       {metrics['latest_date']}
Latest TQQQ Price: ${metrics['latest_price']:.2f}
ret_63:            {metrics['ret_63']:.2f}%
RSI_21:            {metrics['rsi_21']:.2f}

SMA 150 Status: {metrics['sma_status']}
Current Open:   ${metrics['current_open']:.2f}
SMA 150 Value:  ${metrics['sma_150']:.2f}

Note: View the HTML version of this email to see 90-day trend charts.

---
Generated by StockAlert
"""
    
    # HTML email with charts
    html_body = alert_system.generate_html_email(metrics, charts)
    
    logging.info(f"Dashboard Status: {metrics['sma_status']}")
    logging.info(f"Price: ${metrics['latest_price']:.2f} | ret_63: {metrics['ret_63']:.2f}% | RSI_21: {metrics['rsi_21']:.2f}")
    
    # 5. Send Email
    alert_system.send_email(subject, plain_body, html_body)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run TQQQ Dashboard StockAlert check.")
    parser.add_argument("--test-open", type=float, help="Force a specific Open price for testing")
    args = parser.parse_args()
    
    main(test_open=args.test_open)
